---
title: Goals as a chief resident
author: Mara Alexeev
date: '2019-09-02'
slug: goals-as-a-chief-resident
categories: []
tags: [pediatrics]
---

# Tomorrow

Tomorrow is my first day as the chief pediatric resident at Memorial Sloan Kettering Cancer Center in NYC. I have lots of goals for the year, but knowing how chaotic life is in the hospital, I wanted to make sure I wrote them down before they are forgotten! I often find the workflow in hospitals is so busy that it is often to just hard enough to survive the day without building the foundation to try to have more *good* days.

There is tons of material already available to me, so I will need to careful review those to see what just needs to be updated before I know what I need to make myself.

As the year passes I hope to update each of the these bullet points to show my progress.


## Goals  

1. Create templates for:
* Orientation scripts
  * Allow residents to smoothly transition into their rotations
  * Have troubleshooting parts for common issues
* Lectures
  * Create template that allows for easy creation of materials
* Workflow descriptions
  * Outline roles and tasks
    
    
2. Introduce verison control where possible in educational materials
* Creation dates
* Authors and/or contributors
* Last updated
* Estimated date for update
* Contact information

3. Update the resident resource website

4. Redo the resident work room to improve resident workflow and comfort

5. Create a rounding guide
* Senior resident tasks
* Junior resident tasks
* Presentation format and tips

6. Create a well automated resident schedule generator

  
  